### ISSUE TITLE
为什么不是3.0的设计

### ISSUE THREAD

**Issue by GarfieldLover** [debugly/SCNetworkKit#1]

**Comment by debugly** [comment]
AF3.0 跟 2.0 最大的区别应该是去掉了 NSURLConnection 相关的逻辑，仅仅使用 NSURLSession；所以你也可以认为我的部分设计是跟 3.0 一样的，不过我创建库的时候，基本还都是使用的 2.0；

**Comment by GarfieldLover** [comment]
代码组织不一样，意思是现在还用2.0开发？(O_O)？

**Comment by debugly** [comment]
Thank you，我有时间去学习下3.0的组织方式；另外你可能误解了，这个网络框架跟AF没一点关系，更不是基于 2.0 的开发；而是一个全新的框架，基于 NSURLSession 的，借鉴了AF的一些好的思路；

**Comment by GarfieldLover** [comment]
哈哈哈哈哈，好正经
